services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  backend:
    # REPLACE with your actual AWS Account ID and Region
    image: 915658834610.dkr.ecr.ap-south-1.amazonaws.com/jawsight-production-backend:latest
    container_name: backend
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379

  frontend:
    # REPLACE with your actual AWS Account ID and Region
    image: 915658834610.dkr.ecr.ap-south-1.amazonaws.com/jawsight-production-frontend:latest
    container_name: frontend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started

  migrations:
    image: 915658834610.dkr.ecr.ap-south-1.amazonaws.com/jawsight-production-migrations:latest
    container_name: migrations
    restart: "no"
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started

  nginx:
    image: nginx:alpine
    container_name: jawsight_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
