services:
  xray-daemon:
    image: amazon/aws-xray-daemon
    container_name: xray-daemon
    restart: unless-stopped
    ports:
      - "2000:2000/udp"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  backend:
    image: __BACKEND_IMAGE__
    container_name: backend
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
      AWS_XRAY_DAEMON_ADDRESS: xray-daemon:2000

  frontend:
    image: __FRONTEND_IMAGE__
    container_name: frontend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started

  migrations:
    image: __MIGRATIONS_IMAGE__
    container_name: migrations
    restart: "no"
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started

  nginx:
    image: nginx:alpine
    container_name: jawsight_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
