events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    client_max_body_size 100M;

    # Docker internal DNS
    resolver 127.0.0.11 valid=10s;

    proxy_connect_timeout 5s;
    proxy_read_timeout 60s;
    proxy_send_timeout 60s;

    server {
        listen 80 proxy_protocol;
        server_name www.jawsight.online;

        set_real_ip_from 10.0.0.0/16;
        real_ip_header proxy_protocol;

        # -------------------------
        # SOCKET.IO
        # -------------------------
        location /socket.io/ {
            set $backend backend;

            proxy_pass http://$backend:8081;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $proxy_protocol_addr;
            proxy_set_header X-Forwarded-For $proxy_protocol_addr;

            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
        }

        # -------------------------
        # API
        # -------------------------
        location /api/ {
            set $backend backend;

            proxy_pass http://$backend:8081;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $proxy_protocol_addr;
            proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        }

        # -------------------------
        # HEALTH CHECK
        # -------------------------
        location /health {
            set $backend backend;

            proxy_pass http://$backend:8081;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $proxy_protocol_addr;
            proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        }

        # -------------------------
        # ACME CHALLENGE
        # -------------------------
        location /.well-known/acme-challenge/ {
            set $backend backend;

            proxy_pass http://$backend:8081;
        }

        # -------------------------
        # FRONTEND
        # -------------------------
        location / {
            set $frontend frontend;

            proxy_pass http://$frontend:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $proxy_protocol_addr;
            proxy_set_header X-Forwarded-For $proxy_protocol_addr;
        }
    }
}