apiVersion: batch/v1
kind: Job

metadata:
  name: migrate-db

spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: 915658834610.dkr.ecr.ap-south-1.amazonaws.com/jawsight/sequelizer:v3
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
